### ISSUE TITLE
Enable PersistentVolumeClaim name configuration variable

### ISSUE THREAD

**Issue by yagouam** [overhangio/tutor-minio#53]
Hello, I hope this is the right way to trace issues, if not let me know how could I ask for new features

We are trying to enable minio in our kubernetes environment, and as developers we have no permissions for creating PVC and our system administrator teammates want a different name for each PVC per environment.

Currently we cannot modify the PVC name, it is hardcoded in [tutorminio/patches/k8s-volumes](https://github.com/overhangio/tutor-minio/blob/master/tutorminio/patches/k8s-volumes). 

We've tryed to use the [_"k8s-override"_](https://docs.tutor.edly.io/reference/patches.html#k8s-override) hook to modify the previous file but it throws an error while launching

It would be nice to have a configuration variable such as **MINIO_PVC_NAME** to modify PVC name for each environment. 

Thanks in advance

Kind regards!

**Comment by DawoudSheraz** [comment]
Hi, can you provide further details of the errors you encountered when using k8s-override?

**Comment by Faraz32123** [comment]
Hey @yagouam, hope you are doing well.
So regarding the above error that you guys were facing while changing the name for the PVC.
It occurred because you are trying to override the name of the PVC(that name doesn't exists in `volumes.yml`) using `k8s-override` patch and `kubectl apply --kustomize` command fails while overriding the `volumes.yml`.
```
error: no matches for Id PersistentVolumeClaim.v1.[noGrp]/pvc-miniopv-openedx-pre.[noNs]; failed to find unique target for patch PersistentVolumeClaim.v1.[noGrp]/pvc-miniopv-openedx-pre.[noNs]
Error: Command failed with status 1: kubectl apply --kustomize /opt/openedx/manifests-uamx/environments/openedx-stage/env --dry-run=server --validate=true
```

So, what u can do is

- use `k8s-volumes` patch in your plugin or custom plugin that u have made that will look like below. It will create a new PVC with your desired name.

```
{% if not MINIO_GATEWAY %}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-miniopv-openedx-pre
  labels:
    app.kubernetes.io/component: volume
    app.kubernetes.io/name: minio
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{% endif %}
```

- use another patch `k8s-override` in which u will link/override minio deployment in `deployments.yml` with your new pcv like below.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  template:
    spec:
      {% if not MINIO_GATEWAY %}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pvc-miniopv-openedx-pre
      {% endif %}
```
**Note**: You can't change name of the PVC as code is now. With your proposed approach with new variable settings, it will create a new PVC(it won't override the name if someone had already run the launch and created the PVC with default name). So above seems to be the safe approach. Don't forget to migrate data from older PVC to newer PVC if you guys want to change the name for the PVC in your environment and delete the older PVC.
