### ISSUE TITLE
file uploads is not going to minio

### ISSUE THREAD

**Issue by premkanish** [overhangio/tutor-minio#7]
i installed minio plugin and can access it at the url [http://minio.local.overhang.io/](http://minio.local.overhang.io) . After login i can see three buckets as well : _openedx, openedxvideos, openedxuploads._

But if i upload video or images at **file & uploads** in studio , realized that it is getting uploaded in the studio only and i see nothing at minio. Am i missing some extra config. After google i came to know about following:

```
See: https://django-storages.readthedocs.io/en/latest/backends/amazon-S3.html
    VIDEO_UPLOAD_PIPELINE:
    BUCKET: 'www.surfschool.edu'
    ROOT_PATH: 'video'
```
I am confused how to proceed with this in tutor. Please guide me for the same.

_reference_: [https://blog.lawrencemcdaniel.com/setting-up-aws-s3-for-open-edx/](https://blog.lawrencemcdaniel.com/setting-up-aws-s3-for-open-edx/)
